---
# The enterprise-kgateway GatewayClass is created by the Helm chart.
# We just need a Gateway that references it.
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: https
  namespace: kgateway-system
spec:
  gatewayClassName: enterprise-kgateway
  listeners:
  - name: https
    port: 443
    protocol: HTTPS
    hostname: "*.servebeer.com"
    tls:
      mode: Terminate
      certificateRefs:
      - group: ""
        kind: Secret
        name: wildcard-servebeer-tls
        namespace: kgateway-system
    allowedRoutes:
      namespaces:
        from: All
