apiVersion: security.istio.io/v1
kind: AuthorizationPolicy
metadata:
  name: nginx-default-deny
  namespace: nginx
spec:
  targetRefs:
  - kind: Gateway
    group: gateway.networking.k8s.io
    name: waypoint
---
apiVersion: security.istio.io/v1
kind: AuthorizationPolicy
metadata:
  name: nginx-allow-default-ns
  namespace: nginx
spec:
  targetRefs:
  - kind: Gateway
    group: gateway.networking.k8s.io
    name: waypoint
  action: ALLOW
  rules:
  - from:
    - source:
        namespaces: ["default"]
---
apiVersion: security.istio.io/v1
kind: AuthorizationPolicy
metadata:
  name: deny-west-restricted
  namespace: nginx
spec:
  targetRefs:
  - kind: Gateway
    group: gateway.networking.k8s.io
    name: waypoint
  action: DENY
  rules:
  - from:
    - source:
        principals: ["demo-west.local/ns/restricted/sa/default"]
